title: Dev Note
description: My personal dev blog
theme: minima

url: "https://parkjuehwan.github.io"
baseurl: "/dev-note"   # 저장소 이름이 dev-note니까 이렇게 설정

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
